export const ALL_ROOM_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOM_FAIL = 'ALL_ROOM_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ROOM_DETAIL_SUCCESS = 'ROOMS_DETAIL_SUCCESS';
export const ROOM_DETAIL_FAIL = 'ROOMS_DETAIL_FAIL';
